plugins:
  # make remark aware of fontmatter.
  remark-frontmatter:
  # sensible linter defaults see: https://github.com/remarkjs/remark-lint/tree/main/packages/remark-preset-lint-recommended#rules
  remark-preset-lint-recommended:
  # add extra rules
  remark-lint-heading-increment:
  remark-lint-fenced-code-flag:
  remark-lint-first-heading-level:
  # disable some of the sensible defaults given where we are today.
  remark-lint-list-item-indent: false
  remark-lint-final-newline: false
  remark-lint-no-literal-urls: false
  remark-lint-list-item-bullet-indent: false