plugins:
  remark-preset-lint-recommended:
  remark-lint-list-item-indent: false
  remark-lint-final-newline: false
  remark-lint-no-literal-urls: false
  remark-lint-no-shortcut-reference-link: false
  remark-lint-list-item-bullet-indent: false