package actor_interfaces

import (
	actor "github.com/filecoin-project/specs/systems/filecoin_vm/actor"
)

const (
	Method_RewardActor_AwardBlockReward = actor.MethodPlaceholder + iota
)

const (
	Method_StorageMinerActor_ProcessSurprisePoSt = actor.MethodPlaceholder + iota
	Method_StorageMinerActor_ProcessVerifiedElectionPoSt
	Method_StorageMinerActor_NotifyOfSurprisePoStChallenge
	Method_StorageMinerActor_GetOwnerAddr
	Method_StorageMinerActor_GetWorkerAddr
	Method_StorageMinerActor_GetWorkerKey
)

const (
	Method_StorageMarketActor_OnEpochTickEnd = actor.MethodPlaceholder + iota
	Method_StorageMarketActor_AddBalance
	Method_StorageMarketActor_WithdrawBalance
	Method_StorageMarketActor_PublishStorageDeals
	Method_StorageMarketActor_VerifyDealsOnSectorPreCommit
	Method_StorageMarketActor_UpdateDealsOnSectorProveCommit
	Method_StorageMarketActor_GetPieceInfosForDealIDs
	Method_StorageMarketActor_GetWeightForDealSet
	Method_StorageMarketActor_TerminateDealsOnSlashProviderSector
)

const (
	Method_StoragePowerActor_EpochTickEnd = actor.MethodPlaceholder + iota
	Method_StoragePowerActor_AddBalance
	Method_StoragePowerActor_ProcessPowerReport
	Method_StoragePowerActor_ProcessFaultReport
	Method_StoragePowerActor_SlashPledgeForStorageFault
	Method_StoragePowerActor_EnsurePledgeCollateralSatisfied
	Method_StoragePowerActor_CreateStorageMiner
)
