sequenceDiagram
	participant StorageClient
	participant StorageProvider
	participant StorageMarketActor
	StorageClient -->> StorageMarketActor: AddBalance()
	StorageProvider -->> StorageMarketActor: AddBalance()
	StorageClient -->+ StorageProvider: HandleStorageDealProposal(DealProposal, PayloadCID)
	StorageProvider -->- StorageClient: StorageDealProposalRejected
	StorageClient -->+ StorageProvider: HandleStorageDealProposal(DealProposal, PayloadCID)
	StorageProvider -->- StorageClient: StorageDealProposalAccepted
	StorageProvider -->+ StorageClient: graphsync.Pull(PayloadCID)
	StorageClient -->- StorageProvider: graphsync.Push(Payload (IPLD))
	StorageProvider -->> StorageProvider: verifyStorageDealProposal(proposal)
	StorageProvider -->> StorageProvider: verifyPieceCID(pieceCID, payloadCID)
	StorageProvider -->> StorageProvider: signStorageDealProposal()
	StorageProvider -->> StorageClient: StorageDealProposalSigned
	StorageProvider -->> StorageClient: StorageDealCreated
	StorageProvider -->> StorageMarketActor: PublishStorageDeals(newStorageDeals)
	StorageMarketActor -->> StorageMarketActor: generateStorageDealID()
	StorageMarketActor -->> StorageMarketActor: lockFunds()
	StorageMarketActor -->> StorageProvider: DealIDs
	StorageProvider -->> StorageClient: StorageDealProposalPublished (not sure)
	StorageProvider -->> StorageProvider: packDeal/makeDeal
	StorageProvider -->> StorageMinerActor: CommitSector()
	StorageProvider -->> StorageClient: StorageDealCommitted
	CronActor -->> StorageMinerActor: NotifyOfPoStChallenge()
	StorageProvider -->> StorageMinerActor: SubmitPoSt() (not sure who does this)
	StorageMinerActor -->> StorageMinerActor: activateSector:CommittedSector
	StorageMinerActor -->> StorageProvider: NotifyOfOnChainDealStatus(DealActive)
	StorageProvider -->> StorageClient: StorageDealActive
	CronActor -->> StorageMinerActor: NotifyOfPoStChallenge()/CheckPoStSubmissionHappened()
	StorageMinerActor -->> StorageProvider: NotifyOfOnChainDealStatus(DealExpired/DealFailing)
	StorageProvider -->> StorageClient: StorageDealExpired/StorageDealFailing