type Ticket struct {
    // The VRFProof (pi_string in the RFC) is generated by running our VRF on a past ticket
    // in the ticket chain signed with the miner's keypair. This field is 97 bytes long
    // (may be compressible to 80).
    VRFProof Bytes

    // The VDFResult is derived from the VRFResult of the ticket. It is the value that
    // will be used to generate future tickets or ElectionProofs.
    VDFResult Bytes

    // The VDF proves a delay between tickets generated.
    VDFProof Bytes
} // representation tuple
